name: PR Build Check (Linux)

on:
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Install system dependencies for Qt on Linux
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1-mesa-dev libxkbcommon-x11-0 libxcb-cursor0

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.5.*'
          modules: 'qtcharts'
          setup-python: 'false'

      - name: Configure CMake
        run: |
          cmake -B build \
          -DCMAKE_CXX_COMPILER=g++ \
          -DCMAKE_C_COMPILER=gcc \
          -DCMAKE_BUILD_TYPE=Release \
          -DBUILD_TESTING=ON \
          -S .

      - name: Build
        run: cmake --build build --config Release

      - name: Test
        working-directory: build
        run: ctest --output-on-failure
